name: Publish distributions to PyPI and TestPyPI
on:
  push:
    tags:
      - "*"

jobs:
  build-and-publish:
    name: Build and publish distributions to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install wheel
      run: >-
        pip install wheel build
    - name: Build
      run: >-
        python3 -m build
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_TOKEN }}
